## node configurations
node:
  ## the mode of node: authority/storage/watcher
  mode: "authority"
  externalIp: ""
  domainName: ""
  chainWsUrl: ""
  profile: testnet 

## chain configurations
chain:
  ## the name of chain node
  name: "cess"
  ## the port of chain node
  port: 30336

## bucket configurations
bucket:
  port: 15001
  space: 300
  incomeAccount: ""
  signPhrase: ""
  diskPath: ""

## kaleido configurations
kaleido:
  agentPort: 10010
  kaleidoPort: 4001
  bootPeerIds: ""
  stashAccount: ""
  controllerPhrase: ""