## node configurations
node:
  ## the mode of node: tee/storage/validator/rpcnode
  mode: "tee"
  chainWsUrl: ""
  profile: testnet2

## chain configurations
chain:
  ## the name of chain node
  name: "cess"
  ## the port of chain node
  port: 30336

## miner configurations
miner:
  port: 15001
  space: 300
  incomeAccount: ""
  signPhrase: ""
  diskPath: ""

## ceseal configurations
ceseal:
  publicPort: 19999
